apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::442426859105:role/eksctl-expense-cluster-nodegroup-e-NodeInstanceRole-p4w0XdrhVcVs
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - fresher
      userarn: arn:aws:iam::442426859105:user/siree
      username: siree
    
kind: ConfigMap
metadata:
  creationTimestamp: "2025-03-17T08:56:40Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1328"
  uid: 4d0f54d3-95b2-4b3b-aed2-401120ac8aa3